# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: node-todo-cicd
  labels:
    app: node-todo-cicd
spec:
  ports:
    - port: 8080
      targetPort: 8000
      protocol: TCP
  selector:
    app: node-todo-cicd
  type: LoadBalancer