# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: node-todo-app
  labels:
    app: node-todo-app
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: go-web-app
  type: ClusterIP